name: CI build Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        ruby-version: ['2.3', '2.4', '2.5', '2.6']
        include:
          - os: ubuntu-latest
            ES_VERSION: 2.4.6
            ES_DOWNLOAD_URL: >-
              https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.6/elasticsearch-2.4.6.tar.gz
          - os: ubuntu-latest
            ES_VERSION: 5.6.15
            ES_DOWNLOAD_URL: >-
              https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.15.tar.gz
    steps:
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |-
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jre-headless
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - uses: actions/checkout@v3
      - run: 'wget ${{ matrix.ES_DOWNLOAD_URL }}'
      - run: 'tar -xzf elasticsearch-*.tar.gz'
      - run: "sed -i '/UseParNewGC/d' ./elasticsearch-${{ matrix.ES_VERSION }}/bin/elasticsearch.in.sh"
      - run: './elasticsearch-${{ matrix.ES_VERSION }}/bin/elasticsearch -d'
      - run: gem install bundler
      - run: bundle install
      - run: >-
          wget --quiet --waitretry=1 --retry-connrefused --timeout=10
          --output-document=- http://127.0.0.1:9200
      - run: bundle exec rake test
